default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode
  timeout: 5000
  username: vi
  password:

development:
  <<: *default
  database: bujo_dev

test:
  <<: *default
  database: bujo_test

production:
  <<: *default
  database: bujo_prd
