default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode
  timeout: 5000
  username: vi
  password:

development:
  <<: *default
  database: db/dev/bujo

test:
  <<: *default
  database: db/test/bujo

production:
  <<: *default
  database: db/prd/bujo
